// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StardewGuide.Data;

#nullable disable

namespace StardewGuide.Migrations
{
    [DbContext(typeof(FarmDbContext))]
    [Migration("20230705233912_redo")]
    partial class redo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FarmVillager", b =>
                {
                    b.Property<int>("FarmsId")
                        .HasColumnType("int");

                    b.Property<int>("VillagersId")
                        .HasColumnType("int");

                    b.HasKey("FarmsId", "VillagersId");

                    b.HasIndex("VillagersId");

                    b.ToTable("FarmVillager");
                });

            modelBuilder.Entity("StardewGuide.Models.Farm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateCreated")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Farms");
                });

            modelBuilder.Entity("StardewGuide.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("VillagerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VillagerId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("StardewGuide.Models.Villager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Birthday")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Villagers");
                });

            modelBuilder.Entity("FarmVillager", b =>
                {
                    b.HasOne("StardewGuide.Models.Farm", null)
                        .WithMany()
                        .HasForeignKey("FarmsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StardewGuide.Models.Villager", null)
                        .WithMany()
                        .HasForeignKey("VillagersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StardewGuide.Models.Item", b =>
                {
                    b.HasOne("StardewGuide.Models.Villager", "Villager")
                        .WithMany("Best_Gifts")
                        .HasForeignKey("VillagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villager");
                });

            modelBuilder.Entity("StardewGuide.Models.Villager", b =>
                {
                    b.Navigation("Best_Gifts");
                });
#pragma warning restore 612, 618
        }
    }
}
